const words = [
  "Ability - Skill to do something",
"Accept - To receive",
"Accident - Unexpected event",
"Achieve - To succeed",
"Action - Something you do",
"Active - Full of energy",
"Adventure - Exciting experience",
"Advice - Helpful suggestion",
"Afraid - Feeling fear",
"Agree - To have the same opinion",
"Amazing - Very surprising",
"Ancient - Very old",
"Answer - A reply",
"Appear - To become visible",
"Arrange - To put in order",
"Arrive - To reach a place",
"Art - Creative work",
"Attention - Careful notice",
"Available - Ready to use",
"Awake - Not sleeping",
"Balance - Equal position",
"Basic - Simple and important",
"Believe - To think something is true",
"Benefit - Something helpful",
"Bright - Full of light",
"Ability - Skill to do something",
"Accept - To receive",
"Achieve - To succeed",
"Adventure - Exciting experience",
"Beautiful - Very pretty",
"Brave - Courageous",
"Careful - Taking care",
"Challenge - Difficult task",
"Confidence - Belief in yourself",
"Creative - Full of new ideas",
"Decision - Choice",
"Education - Learning process",
"Energy - Strength and power",
"Friendly - Kind and nice",
"Happy - Feeling joy",
"Honest - Truthful",
"Knowledge - Information",
"Practice - Repeated learning",
"Success - Achievement of goals",
"Wisdom - Good judgment"
];

document.querySelector("button").addEventListener("click", function () {
  const random = words[Math.floor(Math.random() * words.length)];
  document.getElementById("result").innerHTML =
    "<h3>Today's Word</h3><p>" + random + "</p>";
});
